apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder 
metadata:
 name: collector                                   <- Name of CLF
 namespace: openshift-logging
 annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
 serviceAccount:
   name: collector                                 <- SA name 
 outputs:
 - name: default-lokistack
   type: lokiStack
   lokiStack:
     target:
       name: logging-loki                          <- Lokistack name 
       namespace: openshift-logging
     authentication:
       token:
         from: serviceAccount
   tls:
     ca:
       key: service-ca.crt
       configMapName: openshift-service-ca.crt      
 pipelines:
  - name: default-logstore
    inputRefs:
     - application
     - infrastructure
    outputRefs:
     - default-lokistack                             <- Outputs Name
