apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
 name: logging-loki
 namespace: openshift-logging
 annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
 managementState: Managed
 size: 1x.demo
 storage:
   schemas:
     - effectiveDate: '2022-06-01'    <------date
       version: v13
   secret:
     name: logging-loki
     type: s3/azure              <----------- on what platform this will be stored
 storageClassName: gp3-csi      <---------- SC name (Storage class)
 tenants:
   mode: openshift-logging
