apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
 name: logging
 annotations:
    argocd.argoproj.io/sync-wave: '4'
spec:
 type: Logging
 logging:
   lokiStack:
     name: logging-loki
